version: '3.8'

services:
  web:
    image: php:8.2-apache
    platform: linux/arm64
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - ./var/www/html:/var/www/html
    depends_on:
      - db
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    command: >
      bash -c "
      chown -R www-data:www-data /var/www/html &&
      chmod -R 755 /var/www/html &&
      apache2-foreground
      "

  db:
    image: mysql:8.0
    platform: linux/arm64
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./var/lib/mysql:/var/lib/mysql

  adminer:
    image: adminer:latest
    platform: linux/arm64
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"
    environment:
      ADMINER_DEFAULT_SERVER: db
